# Generated by Django 4.2.7 on 2023-11-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositoptions',
            name='rsrv_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='depositoptions',
            name='rsrv_type_nm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='savingoptions',
            name='rsrv_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='savingoptions',
            name='rsrv_type_nm',
            field=models.TextField(null=True),
        ),
    ]
