# Generated by Django 4.2.7 on 2023-11-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='views_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='savingproducts',
            name='views_count',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
