# Generated by Django 4.2.7 on 2023-11-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_depositproducts_views_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingproducts',
            name='views_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
